[[components]]

# This component is a "algorithm"
type = "executor"

# The language key for the orchestrator
name = "golang"

[components.build]
# We use go build directive
command = "bash"

# Arguments for the build.
args = ["build.sh"]

[components.run]
# The executable path relative to this file
command = "sorter_go_exe"
