[[components]]
name = "lean"
type = "executor"


[components.build]
# Build command
command = "lake"
# Arguments to build just this executable
args = ["build", "sorter_lean", "-R"]

[components.run]
# The executable path relative to this impafile.toml
command = ".lake/build/bin/sorter_lean"
