[[components]]
name = "java"
type = "executor"

[components.build]
command = "javac"
args = ["-g:none", "Sorter.java"]

[components.run]
command = "java"
args = ["-server", "-XX:+UseParallelGC", "-XX:+AlwaysPreTouch", "-XX:+UseNUMA", "-XX:-UseContainerSupport", "Sorter"]

# [[components]]
# name = "java-aot"
# type = "executor"

# [components.build]
# command = "bash"
# args = ["build.sh"]

# [components.run]
# command = "./sorter_java"
