[[components]]
name = "somombo_unifshuffle"
type = "generator"


[components.build]
# The executable to run (assumes 'lake' is in PATH)
command = "lake"
# The arguments to pass to the command
# We are building the 'data_generator' executable in release mode
args = ["build", "data_generator", "-R"]

[components.run]
# The relative path to the final binary *from this file's directory*
# Lake produces a predictable output path.
command = ".lake/build/bin/data_generator"


[[components]]
name = "somombo_unifshuffle_multi"
type = "generator"


[components.build]
# The executable to run (assumes 'lake' is in PATH)
command = "lake"
# The arguments to pass to the command
# We are building the 'data_generator' executable in release mode
args = ["build", "data_generator_multi", "-R"]

[components.run]
# The relative path to the final binary *from this file's directory*
# Lake produces a predictable output path.
command = ".lake/build/bin/data_generator_multi"
