name = "BenchLabUniformShuffle"
version = "0.1.0"
defaultTargets = ["UnifShuffle"]


[[lean_lib]]
name = "ShuffleSample"

[[lean_lib]]
name = "UnifShuffle"


[[lean_exe]]
name = "data_generator_multi"
root = "Main_Multi"
buildType = "release"

[[lean_exe]]
name = "data_generator"
root = "Main"
# srcDir = "DataGen"

buildType = "release"


[[require]]
name = "Cli"
git = "https://github.com/leanprover/lean4-cli"
rev = "v4.30.0"
