name = "SortBench"
version = "0.3.0"
defaultTargets = ["sorter_lean"]


[[lean_exe]]
name = "sorter_lean"
root = "Main"
buildType = "release"
cflags = ["-O3", "-march=native"]
lflags = ["-static"]
# release = true 


[[require]]
name = "quicksort"
git = "https://github.com/somombo/formalized-quicksort"
rev = "f4257e6e666fe37d951e06b6e04da720e5691143" #"dev_v4.30.0"

