name = "SortBench"
version = "0.4.0"
defaultTargets = ["sorter_lean"]


[[lean_exe]]
name = "sorter_lean"
root = "Main"
buildType = "release"
cflags = ["-O3", "-march=native"]
lflags = ["-static"]
# release = true 


[[require]]
name = "quicksort"
git = "https://github.com/somombo/formalized-quicksort"
rev = "dev"

