name = "SortBench"
version = "0.2.0"
defaultTargets = ["sorter_lean"]



[[lean_exe]]
name = "sorter_lean"
root = "Main"
buildType = "release"
cflags = ["-O3", "-march=native"]
lflags = ["-static"]
# release = true 


[[require]]
name = "quicksort"
git = "https://github.com/somombo/formalized-quicksort"
rev = "84228a9687d72b5a823fdebfc91aacbb78f17408" #"dev_v4.28.0"

