[[components]]

type = "executor"

name = "rust"

[components.build]
command = "cargo"

args = ["build", "--release"]

[components.run]
# The executable path relative to this file
command = "target/release/algo-rust_sorter"
